# docker-compose.yml

version: '3.8'
services:
  # Docker connection string: postgres://postgres:postgres@localhost:5432/

  dev-db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kamsel3112
      - POSTGRES_DB=nest
    ports:
      - '5432:5432'
volumes:
  postgres:
